<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapApp\Backend\MapApp.API\TubieTools_LogisticsOSRM.csproj" />
    <ProjectReference Include="..\TubieTools_Aspire.AppHost\TubieTools_Aspire.AppHost.csproj" />
    <ProjectReference Include="..\TubieTools_Aspire.EnterpriseAutomation\TubieTools_Aspire.EnterpriseAutomation.csproj" />
    <ProjectReference Include="..\TubieTools_PublicAPI\TubieTools_PublicAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PublicAPI\Services\" />
  </ItemGroup>

</Project>
