FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["TubieTools_Aspire.Web/TubieTools_Aspire.Web.csproj", "TubieTools_Aspire.Web/"]
COPY ["TubieTools_Aspire.ServiceDefaults/TubieTools_Aspire.ServiceDefaults.csproj", "TubieTools_Aspire.ServiceDefaults/"]

RUN dotnet restore "TubieTools_Aspire.Web/TubieTools_Aspire.Web.csproj"

COPY . .
WORKDIR "/src/TubieTools_Aspire.Web"
RUN dotnet build "TubieTools_Aspire.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TubieTools_Aspire.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TubieTools_Aspire.Web.dll"]