<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e7c704ef-d914-487f-a7cb-a893f94dfd40</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Workspaces\SanityCheque\SanityCheque\SanityCheque.csproj" />
    <ProjectReference Include="..\TubieTools_Aspire.Web\TubieTools_Aspire.Web.csproj" />
    <ProjectReference Include="..\TubieTools_Forecasting_API\TubieTools_Forecasting_API.csproj" />
    <ProjectReference Include="..\TubieTools_PublicAPI\TubieTools_PublicAPI.csproj" />
    <ProjectReference Include="..\TubieTools_SentimentModel_ProductApi\TubieTools_SentimentModel_ProductApi.csproj" />
    <ProjectReference Include="..\TubieTools_SentimentModel_WebApi\TubieTools_SentimentModel_WebApi.csproj" />
    <ProjectReference Include="..\TubieTools_TensorFlow\TubieTools_TensorFlow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
