// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TubieTools_Machine_Learning
{
    public partial class SentimentModel
    {
        /// <summary>
        /// model input class for SentimentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"reviewer")]
            public string Reviewer { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"date_reviewed")]
            public string Date_reviewed { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"star_rating")]
            public float Star_rating { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"message")]
            public string Message { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"order_id")]
            public string Order_id { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"reviewer")]
            public float[] Reviewer { get; set; }

            [ColumnName(@"date_reviewed")]
            public float[] Date_reviewed { get; set; }

            [ColumnName(@"star_rating")]
            public float Star_rating { get; set; }

            [ColumnName(@"message")]
            public float[] Message { get; set; }

            [ColumnName(@"order_id")]
            public float[] Order_id { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
