// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Transforms;
    public partial class SentimentModel
    {
        public const string RetrainFilePath =  @"C:\Users\xeque\Downloads\EtsySoldOrderItems2022.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Currency", @"Currency"),new InputOutputColumnPair(@"Ship Country", @"Ship Country"),new InputOutputColumnPair(@"Order Type", @"Order Type"),new InputOutputColumnPair(@"Listings Type", @"Listings Type"),new InputOutputColumnPair(@"Payment Type", @"Payment Type")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Quantity", @"Quantity"),new InputOutputColumnPair(@"Discount Amount", @"Discount Amount"),new InputOutputColumnPair(@"Shipping Discount", @"Shipping Discount"),new InputOutputColumnPair(@"Order Shipping", @"Order Shipping"),new InputOutputColumnPair(@"Order Sales Tax", @"Order Sales Tax"),new InputOutputColumnPair(@"Item Total", @"Item Total"),new InputOutputColumnPair(@"Transaction ID", @"Transaction ID"),new InputOutputColumnPair(@"Listing ID", @"Listing ID"),new InputOutputColumnPair(@"Order ID", @"Order ID"),new InputOutputColumnPair(@"VAT Paid by Buyer", @"VAT Paid by Buyer")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Sale Date",outputColumnName:@"Sale Date"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Item Name",outputColumnName:@"Item Name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Buyer",outputColumnName:@"Buyer"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Coupon Code",outputColumnName:@"Coupon Code"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Coupon Details",outputColumnName:@"Coupon Details"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Date Paid",outputColumnName:@"Date Paid"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Date Shipped",outputColumnName:@"Date Shipped"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship Name",outputColumnName:@"Ship Name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship Address1",outputColumnName:@"Ship Address1"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship Address2",outputColumnName:@"Ship Address2"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship City",outputColumnName:@"Ship City"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship State",outputColumnName:@"Ship State"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Ship Zipcode",outputColumnName:@"Ship Zipcode"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Variations",outputColumnName:@"Variations"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"InPerson Discount",outputColumnName:@"InPerson Discount"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"InPerson Location",outputColumnName:@"InPerson Location"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"SKU",outputColumnName:@"SKU"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Currency",@"Ship Country",@"Order Type",@"Listings Type",@"Payment Type",@"Quantity",@"Discount Amount",@"Shipping Discount",@"Order Shipping",@"Order Sales Tax",@"Item Total",@"Transaction ID",@"Listing ID",@"Order ID",@"VAT Paid by Buyer",@"Sale Date",@"Item Name",@"Buyer",@"Coupon Code",@"Coupon Details",@"Date Paid",@"Date Shipped",@"Ship Name",@"Ship Address1",@"Ship Address2",@"Ship City",@"Ship State",@"Ship Zipcode",@"Variations",@"InPerson Discount",@"InPerson Location",@"SKU"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Price",inputColumnName:@"Price",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=20,NumberOfTrees=4,MaximumBinCountPerFeature=254,FeatureFraction=1,LearningRate=0.09999999999999998,LabelColumnName=@"Price",FeatureColumnName=@"Features",DiskTranspose=false}),labelColumnName: @"Price"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 