// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.OpenApi;
using TubieTools_Forecasting_API.Services;

// Configure app
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Price Forecasting API", Description = "Docs for price forecasting API with ONNX models", Version = "v1" });
});

// Register ONNX Price Forecasting Service
// Update the path to your actual ONNX model file
var onnxModelPath = Path.Combine(AppContext.BaseDirectory, "models", "price_forecast_model.onnx");
builder.Services.AddSingleton<IPriceForecastingService>(sp =>
    new OnnxPriceForecastingService(onnxModelPath, sp.GetRequiredService<ILogger<OnnxPriceForecastingService>>())
);

var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Price Forecasting API V1");
    });
}

// Original ML.NET prediction route
app.MapPost("/predict",
    async (MLModel1.ModelInput input) =>
        await Task.FromResult(MLModel1.Predict(input)));

// ONNX single price prediction route
app.MapPost("/predict/onnx/single",
    async (IPriceForecastingService service, float price) =>
    {
        var result = await service.PredictPriceAsync(price);
        return Results.Ok(new
        {
            inputPrice = price,
            forecasts = result.ForecastedPrices,
            lowerBound = result.LowerBound,
            upperBound = result.UpperBound,
            error = result.Error
        });
    })
    .WithName("PredictSinglePrice")
    .Produces(StatusCodes.Status200OK);

// ONNX batch prediction route
app.MapPost("/predict/onnx/batch",
    async (IPriceForecastingService service, List<float> prices) =>
    {
        var results = await service.PredictBatchAsync(prices);
        return Results.Ok(new
        {
            inputPrices = prices,
            predictions = results.Select(r => new
            {
                forecasts = r.ForecastedPrices,
                lowerBound = r.LowerBound,
                upperBound = r.UpperBound,
                error = r.Error
            }).ToList()
        });
    })
    .WithName("PredictBatchPrices")
    .Produces(StatusCodes.Status200OK);

// Health check endpoint
app.MapGet("/health",
    async () => await Task.FromResult(Results.Ok(new { status = "healthy", service = "Price Forecasting API" })))
    .WithName("HealthCheck");

// Run app
app.Run();
